# Generated by Django 6.0.1 on 2026-03-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('customer_id', 'book_id')},
        ),
    ]
